version: "3.9"
services:
  trino:
    image: trinodb/trino:426
    ports:
      - "8080:8080"
    volumes:
      - ./trino/etc:/usr/lib/trino/etc:ro
      - ./trino/catalog:/etc/trino/catalog
      - ./sql:/var/run/sql
      - ./iceberg:/data/iceberg
    depends_on:
      - nessie

  nessie:
    image: ghcr.io/projectnessie/nessie:0.70.0
    ports:
      - "19120:19120"
